# Generated by Django 2.1.1 on 2018-09-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180927_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headimg',
            field=models.ImageField(upload_to='headimg'),
        ),
    ]
