# Generated by Django 2.1.1 on 2018-09-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180927_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headimg',
            field=models.FileField(upload_to='headimg/'),
        ),
    ]
